// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(ChvalyukvaCwContext))]
    partial class ChvalyukvaCwContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfApp1.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Pasword")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pasword");

                    b.HasKey("CustomerId")
                        .HasName("PK__customer__CD65CB858B3C9B06");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("FcustomerId")
                        .HasColumnType("int")
                        .HasColumnName("fcustomer_id");

                    b.Property<int>("FproductId")
                        .HasColumnType("int")
                        .HasColumnName("fproduct_id");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("order_date");

                    b.HasKey("OrderId")
                        .HasName("PK__orders__465962299CD828C5");

                    b.HasIndex("FcustomerId");

                    b.HasIndex("FproductId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("product_name");

                    b.HasKey("ProductId")
                        .HasName("PK__products__47027DF57687EA41");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("WpfApp1.Order", b =>
                {
                    b.HasOne("WpfApp1.Customer", "Fcustomer")
                        .WithMany("Orders")
                        .HasForeignKey("FcustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__orders__fcustome__3B75D760");

                    b.HasOne("WpfApp1.Product", "Fproduct")
                        .WithMany("Orders")
                        .HasForeignKey("FproductId")
                        .IsRequired()
                        .HasConstraintName("FK__orders__fproduct__3C69FB99");

                    b.Navigation("Fcustomer");

                    b.Navigation("Fproduct");
                });

            modelBuilder.Entity("WpfApp1.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WpfApp1.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
